# Generated by Django 4.1.4 on 2023-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.FloatField()),
                ("b", models.FloatField()),
                ("c", models.FloatField()),
                ("d", models.FloatField()),
                ("f", models.FloatField()),
                ("g", models.FloatField()),
                ("h", models.FloatField()),
                ("i", models.FloatField()),
                ("j", models.FloatField()),
                ("k", models.FloatField()),
                ("l", models.FloatField()),
                ("m", models.FloatField()),
                ("n", models.FloatField()),
                ("o", models.FloatField()),
                ("p", models.FloatField()),
                ("q", models.FloatField()),
                ("r", models.FloatField()),
                ("s", models.FloatField()),
                ("t", models.FloatField()),
                ("u", models.FloatField()),
                ("v", models.FloatField()),
                ("w", models.FloatField()),
                ("x", models.FloatField()),
                ("output", models.CharField(max_length=100)),
            ],
        ),
    ]
