# Generated by Django 4.1.4 on 2023-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospitalapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="e",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hospital",
            name="output",
            field=models.IntegerField(),
        ),
    ]
