# Generated by Django 3.2.23 on 2023-11-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0002_hospital_e_alter_hospital_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
